29 UI Backlight Menu
EECS581Team15/WifiLMR pull request #61
Opened 2019-02-18 22:48 UTC by AstralA

Fixes issue #29

## List of Changes

 - Adds UI Backlight functionality.

2019-02-19 00:27 UTC, zjcers requested changes
Two comments about UI design: "Adjust Brightness" should probably be at the top of the screen since it's a header-like thing. The other comment is that the "Save And Go Back" button is packed towards the top of the screen, rather than the bottom. The space below the button looks odd.

2019-02-27 20:03 UTC, zjcers commented
Will not review until merge conflicts are resolved

2019-02-27 22:23 UTC, zjcers approved these changes

2019-03-06 22:09 UTC, jackdweber approved these changes

2019-03-06 22:40 UTC, merged