55 sound in
EECS581Team15/WifiLMR pull request #65
Opened 2019-03-06 22:41 UTC by jackdweber

Fixes issue #

## List of Changes

 - Item 1
 - Item 2

2019-03-07 01:22 UTC, aamirani approved these changes

2019-03-09 04:48 UTC, zjcers requested changes

2019-03-09 04:48 UTC, zjcers commented on radioapp/requirement.txt
> +protobuf==3.4.0
Is protobuf being used directly, or is it a dependency of pymumble?

2019-03-09 04:48 UTC, zjcers commented on radioapp/core/mumble.py
> +    def start(self, callback):
What's the point of the callback here? There doesn't appear to be anything async

2019-03-09 04:48 UTC, zjcers commented on radioapp/core/mumble.py
> +    def initialize(self, host, user, port=64738, password='', certfile=None, keyfile=None, reconnect=True, tokens=[], debug=False):
Shouldn't this be called something like `connect`?

2019-03-09 04:48 UTC, zjcers commented on radioapp/core/mumble.py
> +    def connect(self, callback):
Should this be called something like `on_connect`?

2019-03-13 17:46 UTC, jackdweber commented on radioapp/requirement.txt
> +protobuf==3.4.0
Dependency

2019-03-13 17:49 UTC, jackdweber commented on radioapp/core/mumble.py
> +    def start(self, callback):
I think I originally had connect in here too then moved.

2019-03-13 17:50 UTC, jackdweber commented on radioapp/core/mumble.py
> +    def initialize(self, host, user, port=64738, password='', certfile=None, keyfile=None, reconnect=True, tokens=[], debug=False):
sure

2019-03-13 17:51 UTC, jackdweber commented on radioapp/core/mumble.py
> +    def connect(self, callback):
^

2019-03-14 01:52 UTC, zjcers commented on radioapp/requirement.txt
> +protobuf==3.4.0
I'll approve, but it'd be nice to know if we could remove these extra dependencies since pymumble should bring them in on its own

2019-03-14 01:52 UTC, zjcers approved these changes

2019-03-15 17:29 UTC, merged